apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-service
#  namespace: development
spec:
  type: NodePort
  selector:
#    run: jekyll
#    namespace: development
  ports:
    - name: client
      protocol: TCP
      port: 6379
      targetPort: 6379
    - name: gossip
      protocol: TCP
      port: 16379
      targetPort: 16379
