apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jekyll-site
  namespace: development
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: jekyll-site
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi