# Jekyll POD
apiVersion: v1
kind: Pod
metadata:
  name: jekyll
  labels:
    app: jekyll
spec:
  volumes:
  - name: site
    persistentVolumeClaim:
      claimName: jekyll-site
  containers:
  - name: jekyll
    image: kodekloud/jekyll-serve
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /site
      name: site
 #      subPath: modules
#   env:
#     - name: MYSQL_USERNAME
#       valueFrom:
#       secretKeyRef:
#       name: drupal-mysql-secret
#       key:  D_MYSQL_USERNAME
  initContainers:
    - name: copy-jekyll-site
      image:  kodekloud/jekyl
      command: ["/bin/bash", "-c"]
      args: ["jekyll", "new", "/site"]
      volumeMounts:
      - mountPath: /sites
        name: site
#         subPath: modules
---
apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: development
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 4000
      nodePort: 30097