# Jekyll POD
apiVersion: v1
kind: Pod
metadata:
  name: jekyll
  namespace: development
  labels:
    app: jekyll
    run: jekyll
spec:
  volumes:
  - name: site
    persistentVolumeClaim:
      claimName: jekyll-site
  containers:
  - name: jekyll
    image: kodekloud/jekyll-serve
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /site
      name: site
 #      subPath: modules
  initContainers:
    - name: copy-jekyll-site
      image:  kodekloud/jekyll
      command: ["jekyll", "new", "/site"]
#      args: ["-c","jekyll new /site"]
      volumeMounts:
      - mountPath: /site
        name: site
#         subPath: modules
---
apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: development
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 4000
      nodePort: 30097